import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import StoreProvider from "@/components/StoreProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tfl = localFont({
  variable: "--font-tfl",
  src: [
    {
      path: "../assets/fonts/LondonUndergroundRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/LondonUndergroundMedium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/LondonUndergroundBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/LondonUndergroundHeavy.ttf",
      weight: "900",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-sans">
      <StoreProvider>
        <body
          className={`${inter.variable} ${tfl.variable} ${inter.className} bg-black/95`}
        >
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
